---
- name: Stage instance(s)
  hosts: localhost
  connection: local
  gather_facts: false
  
  tasks:
    - name: 'Provision EC2-Instance'
      ec2:
        count: 1
        group_id: sg-0e1f3aad9b470b80f
        image: ami-0885b1f6bd170450c
        instance_type: t2.micro
        key_name: mykey-NV
        region: us-east-1
        vpc_subnet_id: subnet-00bebd8f6616120ad
        wait: yes
        assign_public_ip: yes
      register: ec2

    - name: Add the newly created host so that we can further contact it
      add_host:
         name: "{{ item.public_ip }}"
         groups: deploy
      with_items: "{{ ec2.instances }}"


    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_ip }}"
        port: 22 
        state: started 
      with_items: "{{ ec2.instances }}"

    - name: accept new ssh fingerprints                                         
      shell: ssh-keyscan -H {{ item.public_ip }} >> ~/.ssh/id_rsa.pub          
      with_items: '{{ ec2.instances }}' 

    - name: Breathing room (Ansible uses python apt, has issues running directly after boot)
      pause: seconds=15

- name: Configuring ElasticSearch
  hosts: deploy
  user: ubuntu 
  become_method: sudo
  become: true
  gather_facts: false
  
  tasks:
    - name: update cache and ignore errors in case of problems
      become: yes
      apt: update_cache=yes
      ignore_errors: yes

    
    - name: install java 8
      become: yes
      apt: 
        name: openjdk-8-jdk
        purge: yes
        state: present

    - name: Set Java home
      shell: sudo echo "JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64" >> /etc/environment

    - name: export Java home
      shell: export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64  

    - name: Download ElasticSearch package
      shell: wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -

    - name: check package list
      shell: echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list

    - name: update cache and ignore errors in case of problems
      become: yes
      apt: update_cache=yes
      ignore_errors: yes

    - name: install elasticsearch
      become: yes
      apt: 
        name: elasticsearch
        purge: yes
        state: present
      notify: restart elasticsearch
    
  handlers:
    - name: restart elasticsearch
      action: service name=elasticsearch state=restarted

 
